### ISSUE TITLE
✨ 메인 페이지 및 검색 페이지 구현(레이아웃, 차트, 표, 검색바, 상세 페이지 등)

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#13]
**📝 DESCRIPTION**
- 관리에 유용한 데이터를 보여줄 차트와 검색 결과를 표시할 표 구현
- 검색 페이지 및 메인 페이지 레이아웃 완성

**☑ TODO**
- [x] 요소별 색 결정
- [x] 차트 구현
- [x] 표 구현
- [x] 실제 데이터로 정상 출력 되는지 확인
- [x] 드롭다운 선택을 포함한 검색바 구현
- [x] 검색 페이지 - 사물함 상세 정보
- [x] 검색 페이지 - 사용자 상세 정보
- [x] 메인 페이지 - 레이아웃
- [x] 메인 페이지 - 차트, 표 배치
- [x] 반납 확인 모달
- [x] 상태 관리 모달
