### ISSUE TITLE
메인서비스 DB 변경에 따른 admin 코드 수정

### ISSUE THREAD

**Issue by eunbi9n** [innovationacademy-kr/42cabi_admin#137]
**📝 DESCRIPTION**
- 메인 서비스의 DB가 바뀐 부분이 있어 이에 맞추어 admin 코드를 수정합니다.

**☑ TODO**
- [x] user entity 수정
- [x] UserStateType enum 삭제
- [x] 관련 메소드 삭제
