### ISSUE TITLE
현황(Status)탭 구현

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#30]
**📝 DESCRIPTION**
- 현황 탭 - 연체자 목록과 고장 사물함 목록

**☑ TODO**
- [x] 페이지 레이아웃
- [x] 연체 API 연결
- [x] 고장 API 연결
- [x] 테이블 row 클릭 -> 해당하는 검색 상세 페이지로 이동

**Comment by Oris482** [comment]
끝!
