### ISSUE TITLE
Frontend 장기대여사물함 관리

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#53]
**📝 DESCRIPTION**
- 장기대여사물함이 도입됨에 따라 해당 사물함의 대여 처리 및 관리 기능 구현

**☑ TODO**
- [ ] 장기 사물함 대여 기능 구현
- [ ] 장기 사물함 관리 테이블(논의 필요)
- [ ] 일반 사물함 <-> 장기 사물함 변환 기능(논의 필요)

**Comment by Oris482** [comment]
없어짐
