### ISSUE TITLE
Frontend 고장 사물함 관련 기능 추가

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#62]
**📝 DESCRIPTION**
- 고장 테이블 들어온 거에 맞춰서 기능 추가

**☑ TODO**
- [x] 고장 사물함 표에 사유 표시
- [x] 사물함 상세 페이지에 고장 사유 표시
- [x] 유저 상세 페이지에 고장 사유 표시
- [ ] 사유 수정 기능 고려

**Comment by Oris482** [comment]
#79번 이슈로 변경
