### ISSUE TITLE
Frontend 메뉴 구조, 페이지 레이아웃 변경

### ISSUE THREAD

**Issue by Oris482** [innovationacademy-kr/42cabi_admin#71]
**📝 DESCRIPTION**
- Task 페이지와 고장/연체 페이지 구조 변경
- 각 페이지 레이아웃 변경

**☑ TODO**
- [x] Task 페이지 왼쪽 부분에 고장 사물함, 밴 사물함 리스트 배치
- [x]  (페이지 이름 미정) 왼쪽 부분에 연체, 밴 유저 리스트 배치
- [x] 위 2개 페이지의 오른쪽 부분에 선택한 요소의 상세 내용 표시(상세페이지 왼쪽 부분)
